### ISSUE TITLE
地図表示画面で表示できる店の数を変更

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#13]
現状の地図表示画面では、一覧に表示される店の数が固定４行に制限されているようなので
これを「地図表示領域内」で「最大１０店の行とマーカー」が「地図移動後に都度店検索・表示される」ように修正する
※ログイン後のサイドメニュー「お店の場所」をタップして表示される画面です
※スクロールされるようになっていなければスクロールされるようにする
※最大１０店とはNameを昇順で並び替えた時の上位１０件
※地図移動後の店検索は、描画されている地図の表示領域に含まれる緯度・経度の店を検索する

**Comment by vndangkeizu** [comment]
@ytakemoto 
@ksvc-dev 
@bachtrunghieu

I created new pull request.
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/31

**Comment by ytakemoto** [comment]
@vndangkeizu 
@ksvc-dev 
@bachtrunghieu
＞※地図移動後の店検索は、描画されている地図の表示領域に含まれる緯度・経度の店を検索する
これって実装されていますか？イメージは以下の通りです。ご確認願います。
![store_map_configuration](https://user-images.githubusercontent.com/15906565/29158187-09beeca4-7de5-11e7-8e45-2cdc0e6e7282.png)

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。
＞※地図移動後の店検索は、描画されている地図の表示領域に含まれる緯度・経度の店を検索する
KSVCの認識が間違ってしまった。
上記の実装がまだ対応しない。

また、地図移動が完了した後、地図に描画されているお店がない場合、リストにお店もないことでしょうか？
そすると、元にお店を戻りたい場合、地図移動の操作だけで実施しますか？（リストにタップできない）

@vndangkeizu 
@ksvc-dev

**Comment by ytakemoto** [comment]
@bachtrunghieu 
@vndangkeizu 
@ksvc-dev 
ヒュウさん
お疲れ様です。竹本です。

ご連絡ありがとうございます。
＞KSVCの認識が間違ってしまった。
＞上記の実装がまだ対応しない。
では、対応をお願いします。

＞また、地図移動が完了した後、地図に描画されているお店がない場合、リストにお店もないことでしょうか？
はい、その時はリストにお店はありません。

＞そすると、元にお店を戻りたい場合、地図移動の操作だけで実施しますか？（リストにタップできない）
別のIssueでお店の検索機能を依頼します。なので今回のIssueでは「元のお店に戻りたい場合は、地図移動の操作だけで実施」で構いません。

宜しくお願いします。

**Comment by vndangkeizu** [comment]
@ytakemoto
@ksvc-dev
@bachtrunghieu

I created new pull request.
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/33

**Comment by ytakemoto** [comment]
@vndangkeizu 
@bachtrunghieu 
@ksvc-dev 
確認しました。対応ありがとうございました。
