### ISSUE TITLE
登録アクションにおける多重クリック・多重タップ防止処理

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#15]
全画面の機能でタップ操作によってDML処理が発生する箇所について、連続でのクリック・連続でのタップによって同一レコードが何回もDML処理されるのを防止する。

**Comment by vndangkeizu** [comment]
@ytakemoto 
@ksvc-dev 
@bachtrunghieu

I created new pull request.
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/34

**Comment by ytakemoto** [comment]
@vndangkeizu 
@ksvc-dev
@bachtrunghieu
確認しました。対応ありがとうございました。
