### ISSUE TITLE
FAQページ追加とFAQデータ取得ポーリング処理追加

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#2]
premise add-on:
![add-on_icon_heroku_scheduler](https://user-images.githubusercontent.com/15906565/29449745-ef385732-8436-11e7-808c-71c5e853fa14.png) Heroku Scheduler

**◆FAQページ追加（web dynoで実行）**
１．サイドメニュー「よくある質問」メニューをクリックするとPostgresのテーブル「Faq__kav」から全レコードを取得してColumn「Title」をリスト表示
２．リストの１つをタップすると、画面がスライドし、タップしたレコードのColumn「ArticleBody__c」の値をHTMLコンテンツとして表示

**◆FAQデータ取得ポーリング処理追加（worker dynoで実行）**
１．REST APIを使って、Salesforceの認証情報（Herokuの環境変数（INTEGRATION_USER_NAME、INTEGRATION_USER_PASSWORD、OAUTH_CLIENT_ID、OAUTH_CLIENT_SECRET、OAUTH_REDIRECT_URL）から取得）の開発組織から、ナレッジオブジェクト「Faq__kav」を全レコード取得してPostgresのテーブル「Faq_kav」と「DELETE ⇒ INSERT」で同期を取る
２．１の機能を「Heroku Scheduler」（addon。無料だが利用するにはcredit情報が必要）で定期的にスケジュール実行できるようにする

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。
【◆FAQページ追加（web dynoで実行）】について
普通なQueryを実行し、レコードを取得すると考えていますが、
「web dynoで実行」という処理がどうな処理を実行するのか？どんな時期で実行するのか？
「web dynoで実行」の処理についてもっと説明もらえますか？
@TranThanhKhai 
@ksvc-dev

**Comment by ytakemoto** [comment]
@bachtrunghieu 
@ksvc-dev 
ヒュウさん
お疲れ様です。竹本です。

＞web dynoで実行
これについては、記載していただいた通り、普通のSQLでQueryしてレコード取得する、という認識で今まで通り開発していただいて問題ありません。
※後述の「worker dynoで実行」と区別するために敢えて記載しました
※web dynoとは、webプロセス（httpプロトコルでServer-Client間を送受信する処理）を実行するためのHerokuのServerリソースの名前です。

逆に「worker dyno」は大丈夫ですか？

**Worker Dynos:** Worker dynos can be of any process type declared in your Procfile, other than “web”. Worker dynos are typically used for background jobs, queueing systems, and timed jobs. You can have multiple kinds of worker dynos in your application. For example, one for urgent jobs and another for long-running jobs. For more information, see [Worker Dynos, Background Jobs and Queueing.](https://devcenter.heroku.com/articles/background-jobs-queueing)

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
@ksvc-dev 

When I render field articlebody__c into html using angularjs, the iframe tag is not being render for serurity, it's mean you can't watch the video.
I can fix this with $sce supported by angularjs, but the document says:

Strict Contextual Escaping (SCE) is a mode in which AngularJS constrains bindings to only render trusted values. Its goal is to assist in writing code in a way that (a) is secure by default, and (b) makes auditing for security vulnerabilities such as XSS, clickjacking, etc. a lot easier.

https://docs.angularjs.org/api/ng/service/$sce

Is this ok if I using this way?

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 

It is ok to use it.
＞https://docs.angularjs.org/api/ng/service/$sce

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
@ksvc-dev 

When I send a DELETE request to salesforce to delete faq__kav record:

> https://ap5.salesforce.com/services/data/v40.0/sobjects/faq__kav/faqRecordId

I got the following error:

> [{"message":"insufficient access rights on object id","errorCode":"INSUFFICIENT_ACCESS_OR_READONLY","fields":[]}]

I tried to delete other object by the same way and it works. I don't know what is different between faq__kav and other object. If my way is wrong, please tell me the way to do it.

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
No deletion request to Salesforce is required.
*Salesforce is the only query request.

Please delete and register within Heroku's Postgres only.

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
@ksvc-dev 

I have created pulll request here:
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/30

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
Heroku Schedulerで「node ./server/faq_worker.js」を設定しましたが、SalesforceのFaq__kavからレコードが取得出来ません。
何か追加の設定が必要ですか？原因を教えてください。
![heroku_scheduler_query_faq__kav](https://user-images.githubusercontent.com/15906565/29075187-a39b7b26-7c8c-11e7-947b-7640dde08ce9.png)

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
@ksvc-dev 

Sorry, you need to add these value to Config Vars:
SFORCE_GET_FAQ_URL : https://ap5.salesforce.com/services/data/v40.0/query
SFORCE_GET_TOKEN_URL : https://login.salesforce.com/services/oauth2/token

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
Config Vars「SFORCE_GET_FAQ_URL」, Please change as follows:

SFORCE_GET_FAQ_URL : /services/data/v40.0/query

Please use "instance_url" included in the response after oauth token request for domain.

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
確認しました。対応ありがとうございました。
