### ISSUE TITLE
認証トークンの検証に失敗したらログインページに強制リダイレクトさせる

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#20]
各ページへ遷移する時に実行される「auth.validateToken」（auth.js）内で、承認トークンの検証に失敗した場合はログインページに強制的にリダイレクトするように修正

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。

本件にも完了しました。
ご確認お願いします。

@ksvc-dev , @TranThanhKhai

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 
ヒュウさん
お疲れ様です。竹本です。

完了のご連絡ありがとうございます。

私の方でレビューしますのでpull requestを作成して下さい。
※もしHeroku上で追加でセットアップが必要なものがあったら併せて連絡下さい
※pull requestは別件でお願いしているIssueと一緒でも別々でも構いません

宜しくお願いします。
