### ISSUE TITLE
ブラウザの機能で画面を更新するとアカウント情報が表示されなくなる

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#24]
ログイン後の画面でブラウザの更新機能（例えばF5キー）にて画面更新すると、アカウント情報が表示されなくなるので、これを表示されるよう修正する。
![update_bug20170731](https://user-images.githubusercontent.com/15906565/28761456-a97367b0-75e9-11e7-89cb-d3d1133f8377.png)

**Comment by vndangkeizu** [comment]
@ytakemoto 
@ksvc-dev 
I have create new pull request
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/26

**Comment by ytakemoto** [comment]
@vndangkeizu 
@ksvc-dev 
確認しました。対応ありがとうございました。
