### ISSUE TITLE
LINE認証機能追加

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#4]
**※本対応にあたりLINE認証用のjsファイル（line.js）を新規作成して下さい（facebook.jsファイルは使わないこと）**
**※本対応にあたりLINEにChannelを登録しておく必要があります。無料で登録できますのでご自身で登録をお願いします**
　⇒https://developers.line.me/web-api/channel-registration
【概要】
１．ログイン画面に表示されている「Facebookアカウントでログイン」ボタンを無くして、代わりに「LINEアカウントでログイン」ボタンを追加
　※ボタンの色はLINEの色合いに変更する
　※ボタンの文字の左側にLINEのアイコンを表示する
![line 85fde1f1-fb0c-461c-8195-a3fad9a37b4c](https://user-images.githubusercontent.com/15906565/28148111-cbbf519a-67bf-11e7-8673-a5efc471f8d7.png)

２．「LINEでログイン」ボタンをタップすると、LINEのサービスに対して認証処理を実行
　**※Herokuの環境変数に下記の設定を追加して下さい**
　⇒【API】https://developers.line.me/web-api/integrating-web-login-v2
　　client_id：環境変数「LINE_CLIENT_ID」の値をセット
　　redirect_uri：環境変数「LINE_REDIRECT_URL」の値をセット
　　state：環境変数「LINE_STATE」の値をセット
３．LINEでの認証が成功したらPostgresのテーブル「Contact」をチェック。該当のユーザが非存在ならContactを新規登録、既に存在していたらContactの情報を取得。
　（※存在有無の判定は下記APIで取得されるuserIdを利用する。取得の際はaccess_tokenが必要）
　⇒新規登録時はLINEからのresponseよりContactの情報をセットする
　⇒【API】https://developers.line.me/web-api/getting-user-profiles
　　contact.lastname：上記APIのレスポンス「displayName」
　　contact.leadsource："Loyalty App"
　　contact.lineuserid__c：上記APIのレスポンス「userId」　**※←Salesforceの取引先責任者にカスタム項目を追加してHeroku ConnectでMapping設定して下さい**
　　contact.pictureURL__c：上記APIのレスポンス「pictureUrl」
　　contact.description：上記APIのレスポンス「statusMessage」
４．以降は通常のログインをした時と同じようにContactでアカウントを制御する

**Comment by bachtrunghieu** [comment]
@ytakemoto
竹本さん
お疲れ様です。ヒュウです。

【https://api.line.me/v2/oauth/accessToken】へのアクセスする場合、「CORS」としてエラーが発生しています。
原因：
サーバが外リンクからサーバにアクセスできる権限がないです。

authorization取得リンクには
https://access.line.me/dialog/oauth/weblogin?client_id=1524762961&redirect_uri=https://demo-nibs-myapp-k.herokuapp.com/oauthcallback.html&state=123abc&response_type=code&display=popup

対応方法がまだわからないです。
APIでアクセス方法が検討中です。
日本側、原因がわかったら、教えていただけませんか？
, @ksvc-dev, @TranThanhKhai @bachtrunghieu

**Comment by ytakemoto** [comment]
@ksvc-dev 
@TranThanhKhai 
@bachtrunghieu 
お疲れ様です。竹本です。

CORSエラーについて、以下の３点を確認願います。

１．もしCORSエラーの詳細なログが取得可能なら、ログの内容を教えてください

２．「POST https://api.line.me/v2/oauth/accessToken」のRequestとRequest Bodyの内容を教えてください。

３．以下の仕様に準拠しているか確認願います
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

宜しくお願いします。

**Comment by ytakemoto** [comment]
@ksvc-dev 
@TranThanhKhai 
@bachtrunghieu 

CORSエラーとは別件ですが追加でお願いです。
authorization code取得でパラメータ指定している「state=123abc」ですが、CSRF対策の為、以下のライブラリを利用してトークン発行の上、access taken取得時にトークンをチェックするように対応をお願いします。

◆ライブラリ
https://github.com/expressjs/csurf

宜しくお願いします。

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。

CORSエラーの詳細なログとRequest Bodyの内容について
添付ファイルにまとめてしました。
ご確認お願いします。
[Evidence_Log.xlsx](https://github.com/ytakemoto-org/demo-nibs-myapp/files/1158600/Evidence_Log.xlsx)

@ksvc-dev , @TranThanhKhai

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 
お疲れ様です。竹本です。

情報共有ありがとうございます。１点確認させて下さい。

LINEのコンソールからコールバックURLは設定していますでしょうか？
（設定している場合、そのURLを教えてください）
＞https://developers.line.me/ba/
※https://developers.line.me/web-api/integrating-web-login-v2　のBefore you beginのリンクから確認可能です

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 

＞https://developers.line.me/ba/
より、サイドメニューの「Technical configuration」を確認願います。

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。

【https://demo-nibs-myapp-k.herokuapp.com/oauthcallback.html】のようなコールバックが設定しています。
ご確認お願いします。

@ksvc-dev , @TranThanhKhai

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。

jsonpにはgetメソッドのみをサーポットしています。
getメソッドの以外がサーポットしていません。

@ksvc-dev , @TranThanhKhai

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 
ヒュウさん
お疲れ様です。竹本です。
jsonpの件は了解しました。POSTメソッドはサポート外なのですね。

本件、ブラウザ（クライアント）側ではなくサーバ側で対応出来ませんか？
※The Same Origin Policyはブラウザ側の制約だったと思うので

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 
ヒュウさん
お疲れ様です。竹本です。

本件、状況は如何ですか？進んでいますでしょうか？

**Comment by bachtrunghieu** [comment]
@ytakemoto 
竹本さん
お疲れ様です。ヒュウです。
返信遅くなり申し訳ありません。
本件には完了しましたです。
確認リンク：https://demo-nibs-myapp-k.herokuapp.com/

また、「Facebookアカウントでログイン」ボタンの処理のコードがソースに
コメントアウトではなくて、削除しても大丈夫でしょうか？

@ksvc-dev , @TranThanhKhai

**Comment by ytakemoto** [comment]
@ksvc-dev 
@bachtrunghieu 
@TranThanhKhai 
ヒュウさん
お疲れ様です。竹本です。

完了のご連絡ありがとうございます。
以下の件ですが
＞また、「Facebookアカウントでログイン」ボタンの処理のコードがソースに
＞コメントアウトではなくて、削除しても大丈夫でしょうか？
削除して問題ありません。

私の方でレビューしますのでpull requestを作成して下さい。
※もしHeroku上で追加でセットアップが必要なものがあったら併せて連絡下さい
　（環境変数は追加されていると思いますが、他にあるれば）
※pull requestは別件でお願いしているIssueと一緒でも別々でも構いません

宜しくお願いします。

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
I have created new pull request
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/22

**Comment by TranThanhKhai** [comment]
@ytakemoto
@bachtrunghieu
@ksvc-dev 
I have created new pull request
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/23

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@bachtrunghieu 
@ksvc-dev 
After authentication process, we call a function in the our page to complete.
If we redirect to LINE Login page instead open popup, we lost the instance of window object on our page, then we can not call that function.

So, I have not figured out how to do this task.

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
LINE loginのredirect先の「oauthcallback.html」の中で、access token取得、profile取得は出来ませんか？
※ Do not use Promise

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@ksvc-dev 
@bachtrunghieu 
I tried this way but i facing another problem with csrf
Every XmlHttpRequest (XHR) send to the server, the server send back to client a new XSRF-TOKEN  using for next XHR.
When LINE redirect to oauthcallback.html, this request using that XSRF-TOKEN but server does not send back new XSRF-TOKEN because this is not XHR
When I send the request to '/getAccessTokenLINE' with old XSRF-TOKEN, I get 403 Forbiden Error because every XSRF-TOKEN is only used once
If I do not use csrf, it works.

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
'/getAccessTokenLINE'をrequestする時だけ、csrfをチェックしないようrouting出来ませんか？

**Comment by TranThanhKhai** [comment]
@ytakemoto 
@ksvc-dev 
@bachtrunghieu 
I need to ignore 3 route: getAccessTokenLINE, getUserProfileLINE, loginLINE.
Is this ok?

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 

ok

**Comment by TranThanhKhai** [comment]
@bachtrunghieu 
@ytakemoto 
@ksvc-dev 
I have created new pull request 
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/25

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
確認しました。対応ありがとうございました。
