### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by ytakemoto** [ytakemoto-org/demo-nibs-myapp#41]
@bachtrunghieu 
@TranThanhKhai 
@ksvc-dev 
HerokuのLogに以下のようなワーニングが表示されているのですが、
#40 のpull requestでPostgres関連の処理が何か変わりましたか？(package.jsonのpgの設定も変わっているようです)

>2017-08-18T10:21:51.991196+00:00 app[web.1]: (node:4) DeprecationWarning: PG.connect is deprecated - please see the upgrade guide at https://node-postgres.com/guides/upgrading

以下を教えてください。
１．このワーニングの意味は？
２．このワーニングはどういう時に表示される？
３．このワーニングを無くす方法は？

宜しくお願いします。

**Comment by TranThanhKhai** [comment]
1. It means the function "connect" is going to be replace by the other in the future. More information here:
[https://node-postgres.com/guides/upgrading](url)
2. Everytime we call that function, the warning show up.
3. Using pool (I use connection URI). More information here:
https://node-postgres.com/features/connecting

I created new pull request here:
https://github.com/ytakemoto-org/demo-nibs-myapp/pull/44

**Comment by ytakemoto** [comment]
@TranThanhKhai 
@bachtrunghieu 
@ksvc-dev 
Thank you for your answer.

I confirmed pull request. Thank you
